version: '3.8'
services:
  db:
    image: postgres:15.0-alpine
    restart: always
    environment:
      # Please actually change username and password before using.
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=polls
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local